name: nanobook
header: |
  <center>
    <img src="/nanobook.png" alt="nanobook logo" width="75%" />

    a **self-hostable** guestbook!
  </center>

# """
# recommended: generate a password hash with:
# bun -e "console.log(await Bun.password.hash('yourpassword'))"
# """

admin:
  username:
  password:

extraFields:
  email:
    type: input
    label: Email
    private: true
    required: false

# """
# note: emojis should be put into the 'public' directory!!
# """

# emojis:
#   love: /emojis/love.gif
